[package]
name = "darkhex-wasm"
version = "0.1.0"
edition = "2021"
description = "WASM bindings for darkhex-core (DSaGe web app)"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
darkhex-core = { path = "../core" }
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
